### ISSUE TITLE
Lucky Parking: Team Agenda and Meeting Minutes

### ISSUE THREAD

**Issue by MichelleRT** [hackforla/lucky-parking#375]
### Overview
This issue tracks the agenda for our weekly meetings so that all team members can:

- look back on the history
- get up to speed faster
- contribute more effectively

#### Issue Template
```
## [Date ]  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369 
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

### Previous Meetings (link to each comment with the date)

**Comment by tmlin1** [comment]
**Notes from Meeting**

- UX team is done with prototype and needs to meet one last time before user testing (Yen will be testing on friends first)
- UX team will meet on Thursday morning to do final fixes and contact Seymour's contact
- Took screenshot for Hack for LA Homepage link 
- Google Drive - can't reach a few folks that are inactive which is why there have been new copies
- Prioritized backlog is higher than ice box  - issues that need to work on priority should be in prioritized backlog. New issue approval for issues to get into ice box, they need to go through the New Issue Approval. 
- Hackathon session - need to formalize an agenda
- Github Admin rights for Michelle and Tiffany?

**Comment by tmlin1** [comment]
## [2022-03-28]  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 2FA Kick Out from GitHub access - Go to Onboarding Meeting on 4/12 (45 mins in) or join Thursday PM meeting at 7:30am pst
- [ ] Add LinkedIn to Roster: https://docs.google.com/spreadsheets/d/1OGhwJFgaNhgLfHF19E1e3JuF4wnbtfSo/edit#gid=1607893055
- [ ] 

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by MichelleRT** [comment]
- See if we need to update the team page on the main Hack for LA website https://www.hackforla.org/projects/lucky-parking
- The date part of the page is not fixed yet but the address part is fixed - Matt will try to fix the date this week.
- UX testing their design on Thursday, tentative 1 PM PST 
- http://www.luckyparking.org/  is the correct website

**Comment by MichelleRT** [comment]
## 2022-04-04  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gregpawin** [comment]
## 2022-04-11  Meeting Agenda
- (Mondays at 6 PM PST)

### FYIs
- @gregpawin taking over meeting minutes.

### Notes from Meeting
- Will need some time to catch up on board hygiene while new PMs are being recruited
- Collected team title names. Will send ticket for updating project page this week.
- Devs are working on some backend issues and waiting for new design approval
- UI/UX is going to interview a new user
- Data is working on EDA colab notebook
- Discussed moving all tasks to the main board
- Update zoom link calendar, modifiable by anyone

**Comment by gordonruby** [comment]
## April 18, 2022  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gordonruby** [comment]
## April 25, 2022  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
    - [ ] [Greg](https://github.com/hackforla/lucky-parking/issues/assigned/gregpawin)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gordonruby** [comment]
## [Date ]  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed
- [ ] Based on the current roster, does everyone have the access they need? https://docs.google.com/spreadsheets/d/1rtou2FkVwKV7-2RKiRDXb2uAq_w0jHakFydzUhoW2dU/edit#gid=1467771315

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gordonruby** [comment]
## May 9, 2022  Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Issue Bash
- [ ] following the meeting with Bonnie last week and [her demo](https://drive.google.com/drive/u/0/folders/1G7CujXzzF7MxVtFiq5EUd9k8zlSA4e_F) for how to add key details to an issue, let's break into groups and complete that for the rest of the issues on the Main Project Board.
- [ ] finish adding labels to the issues that are still missing them (see audit links above)

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gordonruby** [comment]
## May 16, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gordonruby** [comment]
## [May 23, 2022]  Meeting Agenda
- (Mondays at 6 PM PST)
- Zoom link: https://us02web.zoom.us/j/89121722043?pwd=VFlhSUlzbVhpNVBqQmNWd1lSMWFWZz09
- Meeting ID: 891 2172 2043
- pw: 954328

passcode: 954328
### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Format:
-10 mins: Introductions for Yao and Leslie
-5 mins: Gordon reports back from Org meeting with Bonnie
-20 mins: breakout rooms
-20 mins: main room


### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by gordonruby** [comment]
## May 30, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369

**Comment by ychu196** [comment]
Testing

- [ ] test checkbox

**Comment by ychu196** [comment]
## July 25, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
 - [ ] 

### Notes from Meeting


### Task Items

**Comment by ychu196** [comment]
## Aug 1, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Have done a demo of our proposed MVP to Bonnie?
- [ ] History of Lucky Parking
- [ ] UX will do a demo of our MVP


- [ ] We will begin a Rebranding Exercise
- [ ] We will do a Naming Excercise as a 1st step



### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Aug 8, 2022 Meeting Agenda - DRAFT
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] Review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] Finish adding labels to the issue that are still missing them (see audit links above)
- [ ] Review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items:
- [ ] Have we done a demo of our proposed MVP to Bonnie?
- [ ] We will do a Naming Excercise 2nd step?
- [ ] Formalize and Document Product Vision
- [ ] Define our stakeholders
- [ ] Update our Product Roadmap - _up to MVP_



### FYIs
 - [ ] 

### Notes from Meeting:
- A recording of Lucky Parking's history, our MVP was completed; Chu will post it on our wiki soon
- A naming exercise was completed; the list of names will be sent out in a survey to the general public and members of HackforLA to determine which one resonates the most; we will not be surveying Council Members or Community users(the 2 personas) as this will take too much time and is not necessary. 
- Once the name has been selected, we will begin branding
- Chu will connect with Yen to formalize a 3-4month roadmap and a list of stakeholders
- Greg proposed a new feature; we agreed that it was worth pursuing
- We will continue trying to recruit developers



### Next Meeting:

**Comment by ychu196** [comment]
## Aug 15, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Update
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Aug 22, 2022 Meeting Agenda - DRAFT
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] a
- [ ] b
- [ ] c

### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Aug 29, 2022 Meeting Agenda - DRAFT
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Yen - 3min upate on progress on high fidelity 

### FYIs
 - [ ] 

### Notes from Meeting

### Next Meeting:

**Comment by ychu196** [comment]
## Sept 5, 2022 Meeting Agenda - **NO MEETING; Labor day holiday**
- (Mondays at 6 PM PST)

**Comment by ychu196** [comment]
## Sept 12, 2022 Meeting Agenda - DRAFT
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Yen - 3min upate on progress on high fidelity
- [ ] Team - start fleshing out Release Planning/Go to Market strategy on high level, breakout room

**Comment by ychu196** [comment]
## Sept 19, 2022 Meeting Agenda - DRAFT
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Ticket Clean - Chu, Greg
- [ ] GTM - Chu 3min
- [ ] Mike - Update on video demo

### FYIs
 - [ ] 

### Notes from Meeting



### Next Meeting:

**Comment by ychu196** [comment]
## Sept 26, 2022 Meeting Agenda - DRAFT
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Ticket Clean - Chu, Greg
- [ ] GTM - Chu 3min

### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Sept 26, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Updated UX with feedback from Bonnie
- [ ] Agreed to build Web, Web App-like? 
- [ ] Devs will research how to build Native Mobile app(iOS, Android, or both?)
- [ ] MVP 2 will focus more on features and use cases. ie. Thematic map overlays, AI/ML
- [ ] UX will develop an A/B Test to identify temporary Code Name to replace Lucky Parking
- [ ] UX will now start on High Fidelity

### FYIs
 - [ ] 

### Notes from Meeting
- [ ] Chu will confirm with Bonnie re: Maps we can use ie. Google? Mapbox?


### Next Meeting:

**Comment by ychu196** [comment]
## Oct 17, 2022 DRAFT Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [x] Chu to update the team - 5min
- [ ] a
- [ ] b
- [ ] c

### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Oct 24, 2022 DRAFT Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items

- [ ] a
- [ ] b
- [ ] c

### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Nov 7, 2022 DRAFT Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Chu will provide update on Research Templates
- [ ] Chu, Micheal to workshop and resolve Mapbox login issues

### FYIs
 - [ ] 

### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Nov 14, 2022 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [x] Chu will provide update on Research Templates
- [x] Start prepping for End of Year retrospective later in dec
   - [x] Design
   - [x] Data Science
   - [x] Devs
   - [x] New members 

### FYIs


### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## Nov 28, 2022 DRAFT Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [x] Coduct End of Year retrospective 1 of 2(to suit people's schedules)
   - [x] Design
   - [x] Data Science
   - [x] Devs
   - [x] New members 

### FYIs


### Notes from Meeting


### Next Meeting:

**Comment by ychu196** [comment]
## DECEMBER
During the month of December, we did not have any formal meetings.

**Comment by ychu196** [comment]
## January XX 2023 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
 - [ ] review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Chu - Update
 - [ ] abc

What went well?
What should we improve?
What should we keep doing?
How can we help your careers?
What skills, tech, knowledge do you need for your jobs?

### FYIs


### Notes from Meeting
- December is officially the end of work; folks can continue on if they wish but resources/support from Hack4LA may not be available

**Synthesis and Summary of End of Year Retrospective:**

Design:
- The Design/UX team came together really well, strategic direction was clearer/better aligned now that we have stability;
- Earlier in the year we had a lot of change and hiccups, not anymore
- Training on "How to be a Design Lead"
- Need more regular interaction with devs; currently it's too adhoc;

Product:
- Build out our product roadmap in more detail; too high level
- Need to recruit more devs
- Get more aligned on vision, it's getting muddied due to changes

Devs, Data Science:
- Active mentorships/coaching – more personal touch instead of just posting tickets
- More opportunity to do Data science, data analysis,  gis, data visualization, data engineering, data cleaning
- Should have documentation on setting up dev environment for PC and Mac
- More tasks for devs to do; not enough tasks for devs
- Devs want to practice by creating javascript projects, sql projects, data sciencey projects
- Learn about software architecture and technical design
- Some want more understanding of the business side of things
- How to lead and manage a dev team
- As a dev team, feels more cohesive than before

General:
- some personal initiative is necessary to develop their own skills but this is hard due to work/personal committments
- we can leave reviews of each other on LinkedIn
- Everyone is supportive and helpful - keep doing this
- Onboarding is good, meetings well organized
- Need to understand where we are at the dev side of things
- When the devs left, we were lost in terms of what they did and why they did it; Where the code is? No dev documentation


### Next Meeting:

**Comment by parcheesime** [comment]
## 05/05/25 Meeting Agenda
- (Mondays at 6 PM PST)

### Prework to prep for meeting
- [ ] Review PM/Org Meeting Notes https://github.com/hackforla/lucky-parking/issues/354

### Recurring items: 
- [ ] Review any issues that are in the [new issue approval column](https://github.com/hackforla/lucky-parking/projects/3#column-17941639)
- [ ] Accountability and Support Check.
  - [ ] Review assignments for each Team member
- [ ] Finish adding labels to the issues that are still missing them (see audit links above)
- [ ] Review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
  - [ ] #

### New Items
- [ ] Project Final Push: Goals
  - [ ] Get alignment on the remaining work needed to finish the project
  - [ ] Confirm what’s functional and what can be completed using test or dummy data
  - [ ] Identify and assign final issues in GitHub to move toward a soft launch
  - [ ] Clarify any blockers (e.g., database readiness, admin access)
  - [ ] Establish a realistic timeline for wrapping up the project or launching a test version

- [ ] Project Check-In
  - [ ] What’s working now?
  - [ ] What’s still in progress or blocked?

- [ ] Final Functionality Review
  - [ ] What is required for a complete experience?
  - [ ] Can we move forward using dummy/test data?
  - [ ] Any features we can cut or simplify?

- [ ] Task Review & Assignments
  - [ ] Go over remaining GitHub issues
  - [ ] Identify issues to push post-launch

- [ ] Timeline & Coordination
  - [ ] Can we estimate a soft launch date?
  - [ ] Who are the stakeholders?
  - [ ] Do we want weekly check-ins or async updates?

- [ ] Carry over items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Add new issues to be created to https://github.com/hackforla/lucky-parking/issues/369
